version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout      

      - run:
          name: install dependencies
          command: |
            # conda env create -q || conda env update -q
            # source activate adj
            conda install -c conda-forge -y numpy
            conda install -c conda-forge parameterized 
            conda install -qy conda-build anaconda-client pytest pytest-cov

            conda config --set auto_update_conda no
            conda info -a
            #conda build conda.recipe --no-test
            #conda install -y --use-local nbo2graph      

      - run:
          name: run tests
          command: |
            # source activate adj
            pytest --color=yes -v --cov=nbo2graph tests
            conda install -c conda-forge codecov
            codecov -t 5b64d748-cff0-4d85-b6a2-da755deb269b

      - store_artifacts:
          path: test-reports
          destination: test-reports
